Update engine/system/win/sys_local.h
Fix Error C2440 'initializing': cannot convert from 'nullptr' to 'bool'

Co-authored-by: Fish013 <326399+Fish013@users.noreply.github.com>